In [1]:
import pandas as pd
import numpy as np

In [2]:
spending = pd.read_csv('../output/dist-spending.csv')

In [3]:
population = pd.read_csv('../data/dist-population.csv')

In [4]:
population = population.drop(columns=['Constituency type', 'Total electors 2016', 'Attainers 2015', 'Attainers 2016', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12'])

In [5]:
population['eu_spending'] = 0

In [6]:
spending.loc[spending['parliamentary_constituency_name'] == 'Sedgefield'].project_eu_contribution_gbp

485    32622247.0
Name: project_eu_contribution_gbp, dtype: float64

In [20]:
spending.loc[spending['parliamentary_constituency_name'] == 'Sedgefield'].project_eu_contribution_gbp.values[0]

32622247.0

In [30]:
not spending.loc[spending['parliamentary_constituency_name'] == 'Wales'].empty

False

In [35]:
for index, row in population.iterrows():
    if not spending.loc[spending['parliamentary_constituency_name'] == row['Parliamentary constituency']].empty:
        population.loc[index, 'eu_spending'] = spending.loc[spending['parliamentary_constituency_name'] == row['Parliamentary constituency']]['project_eu_contribution_gbp'].values[0]

In [36]:
population

,Code,Parliamentary constituency,Total electors 2015,eu_spending
0,K02000001,United Kingdom,44722004,0.000000e+00
1,E92000001,England,37399942,0.000000e+00
2,W92000004,Wales,2181841,0.000000e+00
3,S92000003,Scotland,3896852,0.000000e+00
4,N92000002,Northern Ireland,1243369,0.000000e+00
5,E14000530,Aldershot,69903,5.024191e+08
6,E14000531,Aldridge-Brownhills,58359,1.258183e+07
7,E14000532,Altrincham and Sale West,69719,4.616349e+07
8,E14000533,Amber Valley,64454,1.950242e+06
9,E14000534,Arundel and South Downs,75321,3.655379e+07
10,E14000535,Ashfield,76490,4.847399e+06
11,E14000536,Ashford,82527,5.391504e+07
12,E14000537,Ashton-under-Lyne,65941,3.018090e+05
13,E14000538,Aylesbury,77463,2.334038e+07
14,E14000539,Banbury,85398,9.060593e+07
15,E14000540,Barking,72314,6.222677e+06
16,E14000541,Barnsley Central,60767,1.680633e+07
17,E14000542,Barnsley East,65344,0.000000e+00
18,E14000543,Barrow and Furness,67777,3.757217e+06
19,E14000544,Basildon and Billericay,64885,4.070511e+07
20,E14000545,Basingstoke,78026,5.210989e+08
21,E14000546,Bassetlaw,76764,1.631092e+07
22,E14000547,Bath,60966,4.068474e+08
23,E14000548,Batley and Spen,75961,4.131257e+06
24,E14000549,Battersea,69924,1.609627e+07
25,E14000550,Beaconsfield,73984,8.642211e+07
26,E14000551,Beckenham,66067,3.775300e+06
27,E14000552,Bedford,70259,5.264705e+07
28,E14000553,Bermondsey and Old Southwark,80174,5.380617e+08
29,E14000554,Berwick-upon-Tweed,55548,2.761931e+07
...,...,...,...,...
625,S14000048,North Ayrshire and Arran,70779,9.825383e+06
626,S14000049,North East Fife,56716,4.572138e+08
627,S14000050,Ochil and South Perthshire,74680,2.677149e+07
628,S14000051,Orkney and Shetland,33229,2.322391e+08
629,S14000052,Paisley and Renfrewshire North,64246,3.021374e+07
630,S14000053,Paisley and Renfrewshire South,58803,6.757796e+07
631,S14000054,Perth and North Perthshire,69964,2.937483e+08
632,S14000055,"Ross, Skye and Lochaber",51817,2.202061e+07
633,S14000056,Rutherglen and Hamilton West,78671,3.368335e+07
634,S14000057,Stirling,63704,2.681246e+08
635,S14000058,West Aberdeenshire and Kincardine,72327,3.845682e+07
636,S14000059,West Dunbartonshire,66725,2.773494e+07
637,N06000001,Belfast East,63358,3.029454e+08
638,N06000002,Belfast North,69041,5.314325e+07
639,N06000003,Belfast South,64876,8.798377e+08
640,N06000004,Belfast West,62643,4.071376e+07
641,N06000005,East Antrim,63304,2.524476e+07
642,N06000006,East Londonderry,67359,2.535350e+08
643,N06000007,Fermanagh and South Tyrone,70238,1.935871e+07
644,N06000008,Foyle,70602,1.526256e+08
645,N06000009,Lagan Valley,71855,2.074875e+07
646,N06000010,Mid Ulster,68327,3.487095e+07
647,N06000011,Newry and Armagh,78158,1.923849e+07
648,N06000012,North Antrim,76278,2.657761e+07
649,N06000013,North Down,64700,8.339232e+06
650,N06000014,South Antrim,68020,6.595384e+07
651,N06000015,South Down,75606,2.933507e+06
652,N06000016,Strangford,64750,4.940547e+07
653,N06000017,Upper Bann,80251,3.920914e+07
654,N06000018,West Tyrone,64003,2.066823e+07

In [42]:
population = population.rename(index=str, columns={"Code": "code", "Parliamentary constituency": "constituency", "Total electors 2015": "tot_electors_2015"})

In [44]:
population['spending_per_elector'] = round(population['eu_spending']/population['tot_electors_2015'], 2)

In [46]:
population.loc[population['constituency'] == 'East Ham']

,code,constituency,tot_electors_2015,eu_spending,spending_per_elector
154,E14000679,East Ham,82810,116195539.0,1403.16

In [47]:
population.to_csv('../output/pop-and-spending.csv')